name: 'Build HPCC Project'
description: 'Build one of HPCC Project: platform, clienttools, docs and plugins'
inputs:
  platformBranch:
    description: 'HPCC Platform branch or tag'
    required: false
  githubUser:
    description: 'github user. The default is hpcc-systems'
    required: false
  buildCategory:
    description: 'One of HPCC Project: platform, clienttools, docs and plugins'
    required: true

outputs:
  result:
    description: 'Build succeed or failed'

runs:
  using: "composite"
  steps:
    - run: echo "INPUT ${INPUT_BUILDCATEGORY}"
      shell: bash
    - run: bin/main.sh
      shell: bash
