# File: .github/workflows/build-docs.yml

on: 
  push:
    branches:
      - "master"

name: Build-Documentation

jobs:
  build:
    
    name: build-docs
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./ 
        with:
          build_category: docs
      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: html-help
          path: |
            /home/runner/work/hpcc-build/hpcc-build/build/docs/EN_US/HTMLHelp/html_help_EN_US-7.13.0-trunk0.zip