# File: .github/workflows/build-docs.yml

on: 
  push:
    branches:
      - "master"

name: Build-Documentation

jobs:
  build:
    
    name: build-docs
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./ 
        